version: '3'

networks:
  es-shared:
    external:
      name: es-shared

services:
  heartbeat:
    image: elastic/heartbeat:7.7.0
    container_name: heartbeat01
    user: heartbeat
    environment:
      CERTS_DIR_HEARTBEAT: ${CERTS_DIR_HEARTBEAT}
    command: ["--strict.perms=false"]
    volumes:
      - ${PWD}/config/heartbeat01.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - ${PWD}/data/heartbeat01:/usr/share/heartbeat/data
      - ${PWD}/config/certs:${CERTS_DIR_HEARTBEAT}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - es-shared