filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/test.log
    fields:
      from: spring
    fields_under_root: true

output.logstash:
  hosts: ["logstash01:5044"]
  bulk_max_size: 1024
  ssl.certificate_authorities: ["${CERTS_DIR_FILEBEAT}/ca/ca.crt"]
  ssl.certificate: "${CERTS_DIR_FILEBEAT}/filebeat01/filebeat01.crt"
  ssl.key: "${CERTS_DIR_FILEBEAT}/filebeat01/filebeat01.key"

#============================== X-Pack Monitoring ===============================
# Use internal collection to send monitoring data
# Starting in Filebeat version 7.2, legacy collection settings are deprecated and will be removed in version 8.0.0
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://es02:9200"]
    #username: "beats_system"
    username: "elastic"
    password: "123456"

    # Use SSL settings for HTTPS.
    ssl.enabled: true

    # List of root certificates for HTTPS server verifications
    ssl.certificate_authorities: ["${CERTS_DIR_FILEBEAT}/ca/ca.crt"]

    # Certificate for SSL client authentication
    ssl.certificate: "${CERTS_DIR_FILEBEAT}/filebeat01/filebeat01.crt"

    # Client certificate key
    ssl.key: "${CERTS_DIR_FILEBEAT}/filebeat01/filebeat01.key"

