logging:
  level:
    org:
      jooq: DEBUG
server:
  port: 8088
spring:
  application:
    name: jooq
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://127.0.0.1:5432/my-jooq
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  # 此处配置在启动主程序时加载
  flyway:
    # 是否启用flyway
    enabled: true
    ## 编码格式，默认UTF-8
    encoding: UTF-8
    ## 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    ## 迁移sql脚本文件名称的前缀，默认V
    sqlMigrationPrefix: V
    ## 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sqlMigrationSeparator: __
    # 迁移sql脚本文件名称的后缀
    sqlMigrationSuffixes: .sql
    # 迁移时是否进行校验，默认true
    validateOnMigrate: true
    # 设置为true，当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baselineOnMigrate: true
    # postgres10没有引入这个不提示错误，postgres12没有引入会报错
    schemas: jooq
  jooq:
    sql-dialect: POSTGRES
    # 配置未生效，原因是未将自定义的schema的bean注入到容器

  errors:
    controller: true
    attributes: true
    controller-advice: true


elastic:
  stack:
    es:
      hosts: "zsx-2.local:9200"
      scheme: http
    logstash:
      url: http://zsx-2.local:8088
      username: logstash_writer_user
      password: 123456
      send-timeout: 5000
      send-interval: 5000
