version: '3.8'

networks:
  es-shared:
    external:
      name: es-shared

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      CERTS_DIR: ${CERTS_DIR}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # xpack.license.self_generated.type: trial
    volumes:
      - /data/operations/data/es01:/usr/share/elasticsearch/data
      - /data/operations/config/certs:$CERTS_DIR
      - ${PWD}/config/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - es-shared
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      CERTS_DIR: ${CERTS_DIR}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # xpack.license.self_generated.type: trial
    volumes: 
      - /data/operations/data/es02:/usr/share/elasticsearch/data
      - /data/operations/config/certs:$CERTS_DIR
      - ${PWD}/config/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9200
    networks:
      - es-shared


  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana01
    environment:
      elasticsearch.hosts: http://es01:9200
    ports:
      - 5601:5601
    networks:
      - es-shared


