version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2184:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.110
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.110:2184