version: '3'
services:
    zook01:
        image: zookeeper:3.6.1
        restart: always
        container_name: zook01
        ports:
            # client port
            - 2181:2181
            # follower port
            - 2888:2888
            # election port
            - 3888:3888
        environment:
            # this zookeeper's id, and others zookeeper node distinguishing
            ZOO_MY_ID: 1
            # zookeeper services list
            ZOO_SERVERS: ${ZOO_SERVERS}
        # 单台主机不能设置为host，默认网络驱动为bridge
        # network_mode: host
    zook02:
        image: zookeeper:3.6.1
        restart: always
        container_name: zook02
        ports:
            - 2182:2181
            - 2889:2888
            - 3889:3888
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: ${ZOO_SERVERS}
        # network_mode: host
    zook03:
        image: zookeeper:3.6.1
        restart: always
        container_name: zook03
        ports:
            - 2183:2181
            - 2890:2888
            - 3890:3888
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: ${ZOO_SERVERS}
        # network_mode: host