metricbeat.modules:
  #-------------------------------- System Module --------------------------------
  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      #- core           # Per CPU core usage
      #- diskio         # Disk IO
      #- filesystem     # File system usage for each mountpoint
      #- fsstat         # File system summary metrics
      #- raid           # Raid
      #- socket         # Sockets and connection info (linux only)
      #- service        # systemd service information
    period: 100s
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    processors:
      - add_fields:
          # target: ''时，属性设置为顶级属性，否则属于target的value值下的属性
          target: ''
          fields:
            env: test
            source: facility
            type: metrics
            from: host

  #---------------------------- redis Status Module ----------------------------
  - module: redis
    metricsets: ["info", "key", "keyspace"]
    hosts: ["192.168.1.110:6379", "192.168.1.121:6379", "192.168.1.110:7000"]
    period: 100s
    #password: foobared
    # 收集名称以test- *开头且限制为20个键的所有键的信息
    key.patterns:
      - pattern: 'test-*'
        limit: 20

    processors:
#      - include_fields:
#          fields: ["beat", "metricset", "redis.info.stats"]
      - add_fields:
          target: ''
          fields:
            env: test
            source: facility
            type: metrics
            from: redis

  #---------------------------- docker Status Module ----------------------------
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 100s
    enabled: true
    processors:
      - add_fields:
          target: ''
          fields:
            env: test
            source: facility
            type: metrics
            from: docker

  #----------------------------- postgresql output --------------------------------
  - module: postgresql
    enabled: true
    metricsets:
      # Stats about every PostgreSQL database
      - database

      # Stats about the background writer process's activity
      - bgwriter

      # Stats about every PostgreSQL process
      - activity

    period: 10s
    processors:
      - add_fields:
          target: ''
          fields:
            env: test
            source: facility
            type: metrics
            from: postgres
    # The host must be passed as PostgreSQL URL. Example:
    # postgres://localhost:5432?sslmode=disable
    # The available parameters are documented here:
    # https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
    # [postgres://][user:pass@]host[:port][?options]
    hosts: ["postgres://172.18.0.10:5433"]

    # Username to use when connecting to PostgreSQL. Empty by default.
    username: test

    # Password to use when connecting to PostgreSQL. Empty by default.
    password: test

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["192.168.1.110:9600"]



