version: '3.1'

networks:
  shared:
    external:
      name: shared

services:
  nginx:
    image: nginx:stable
    container_name: my-nginx
#    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $(PWD)/config/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/log/nginx:/var/log/nginx
      - ${PWD}/../apps/html:/usr/share/nginx/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shared

